version: "3.9"

services:
  web:
    stdin_open: true
    tty: true
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./projekt:/projekt
    ports:
      - "8000:8000"
