# Generated by Django 4.0.4 on 2022-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nazwisko',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wiek',
            field=models.IntegerField(null=True),
        ),
    ]
