# Generated by Django 4.0.4 on 2022-05-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_imie_user_nazwisko_user_wiek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
