# Generated by Django 4.0.4 on 2022-05-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_avatar_user_opis_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='opis',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
