# Generated by Django 4.0.4 on 2022-05-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_imie_alter_user_nazwisko_alter_user_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wiek',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
