# Generated by Django 4.0.3 on 2022-06-05 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_wiek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='id_uzytkownika',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pushups',
            old_name='id_uzytkownika',
            new_name='user',
        ),
    ]
