# Generated by Django 4.0.4 on 2022-06-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_pushups_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushups',
            options={'verbose_name_plural': 'Pushups'},
        ),
    ]
