# Generated by Django 4.0.4 on 2022-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_pushups_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='limit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
